F
======================================================================
FAIL: test_small_prime (__main__.SieveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peters43/209_18S/admin/grading/a3/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '39 3 13\nNumber of filters = 4' != '39 is prime\nNumber of filters = 1'
- 39 3 13
+ 39 is prime
- Number of filters = 4?                     ^
+ Number of filters = 1?                     ^


----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (failures=1)
